### ISSUE TITLE
Unable to Load Config Flow error after adding through HACS

### ISSUE THREAD

**Issue by 40pints** [jdeath/Bedrock-Homeassistant#5]
I am running Home Assistant: core-2021.12.10
on HASSOS: supervisor-2021.12.2
on a Raspberry Pi 4.

I have installed via HACS and have restarted the home assistant core. 

When going to the integrations page and adding Minecraft Server, I have a popup stating "Please wait while Minecraft Server is being setup" but then after a minute or so I get a "config flow could not be loaded".

I cannot find any log entries showing what is happening, any ideas on how to resolve this?

**Comment by jdeath** [comment]
I never have seen this error. Are you sure you got the server IP and port correctly and selected bedrock? You can DM me the IP/port on the home assistant forums and I can check if it works for me.

**Comment by 40pints** [comment]
> I never have seen this error. Are you sure you got the server IP and port correctly and selected bedrock? You can DM me the IP/port on the home assistant forums and I can check if it works for me.

HI, I don't even get to the point of choosing bedrock and entering the server settings. The integration's options do not load. I am not sure where the logs are for integration UI items in HomeAssistant

**Comment by 40pints** [comment]
Apologies, it would appear that this has been resolved by rebooting the whole Raspberry Pi (not just restarting home assistant). 
After doing that the integration worked perfectly and I am easily connected to my server. Thank you for producing this, it is awesome.
