### ISSUE TITLE
docker - getmac function fails

### ISSUE THREAD

**Issue by MrCaffeen** [jdeath/Bedrock-Homeassistant#7]
Looks like the python getmac function doesn't work to always reliably get mac address is there another alternative we can have as a fallback. Will try and assist in also having an if statement mac returns $null goto fallback option to generate an alternative.

**Comment by jdeath** [comment]
This integration just forked the old Minecraft integration to add bedrock. I use the same python library, but do not develop it. If it is an issue with the library, I do not know how to fix.

**Comment by MrCaffeen** [comment]
Will follow it up the chain to see if they have changed anything in their code. so will let you know how we can fix this.

**Comment by MrCaffeen** [comment]
will close this issue off as it is not a problem with the code. 
it's something to do with running homeassistant in a docker, and not able to get access to the arp table to generate. 
will throw this as an issue to the main code, as your code matches.
